// API endpoint configuration for easy maintenance
export const BASE_URL = "";
export const API_ENDPOINTS = {
  GET_USER_PROFILE: `${BASE_URL}/api/v1/users/profile`,
  GET_USER_INFO: `${BASE_URL}/api/v1/users`,
  GET_ADDRESSES: `${BASE_URL}/api/v1/addresses`,
  CREATE_ADDRESS: `${BASE_URL}/api/v1/addresses`,
  UPDATE_ADDRESS: (addressId) => `${BASE_URL}/api/v1/addresses/${addressId}`,
  DELETE_ADDRESS: (addressId) => `${BASE_URL}/api/v1/addresses/${addressId}`,
  GET_CART: `${BASE_URL}/api/v1/cart`,
  ADD_CART_ITEM: `${BASE_URL}/api/v1/cart/add`,
  INCREMENT_CART_ITEM: (variantId) => `${BASE_URL}/api/v1/cart/increment/${variantId}`,
  DECREMENT_CART_ITEM: (variantId) => `${BASE_URL}/api/v1/cart/decrement/${variantId}`,
  REMOVE_CART_ITEM: (variantId) => `${BASE_URL}/api/v1/cart/${variantId}`,
  CLEAR_CART: `${BASE_URL}/api/v1/cart/clear`,
  SEND_OTP: `${BASE_URL}/api/v1/auth/send-otp`,
  SEND_OTP_LOGIN: `${BASE_URL}/api/v1/auth/login/send-otp`,
  VERIFY_OTP: `${BASE_URL}/api/v1/auth/verify-otp`,
  SEND_LINK_PHONE_OTP: `${BASE_URL}/api/v1/auth/link-phone/send-otp`,
  VERIFY_LINK_PHONE_OTP: `${BASE_URL}/api/v1/auth/link-phone/verify`,
  GOOGLE_AUTH: `${BASE_URL}/api/v1/auth/google`,
  LOGOUT: `${BASE_URL}/api/v1/auth/logout`,
  CREATE_CHECKOUT: `${BASE_URL}/api/v1/checkout`,
  GET_ORDERS: `${BASE_URL}/api/v1/orders`,
  GET_ORDER_DETAILS: (id) => `${BASE_URL}/api/v1/orders/${id}`,
  // Wishlist
  GET_WISHLIST: `${BASE_URL}/api/v1/wishlist`,
  ADD_WISHLIST_ITEM: (productId) => `${BASE_URL}/api/v1/wishlist/add/${productId}`,
  ADD_WISHLIST_ITEM_WITH_VARIANT: (productId, variantId) => `${BASE_URL}/api/v1/wishlist/add/${productId}/variant/${variantId}`,
  REMOVE_WISHLIST_ITEM: (productId) => `${BASE_URL}/api/v1/wishlist/${productId}`,
  REMOVE_WISHLIST_ITEM_WITH_VARIANT: (productId, variantId) => `${BASE_URL}/api/v1/wishlist/${productId}/variant/${variantId}`,
  CLEAR_WISHLIST: `${BASE_URL}/api/v1/wishlist/clear`,
  CHECK_WISHLIST_ITEM: (productId) => `${BASE_URL}/api/v1/wishlist/check/${productId}`,
  CHECK_WISHLIST_ITEM_WITH_VARIANT: (productId, variantId) => `${BASE_URL}/api/v1/wishlist/check/${productId}/variant/${variantId}`,
  GET_COUPONS: `${BASE_URL}/api/v1/coupons`,
  VERIFY_COUPON: `${BASE_URL}/api/v1/coupons/verify`,
  GET_CATEGORIES: `${BASE_URL}/api/v1/categories`,
  GET_CATEGORY: (id) => `${BASE_URL}/api/v1/categories/${id}`,
  GET_PRODUCTS: `${BASE_URL}/api/v1/products`,
  GET_PRODUCT: (id) => `${BASE_URL}/api/v1/products/${id}`,
  SUBMIT_QUERY: `${BASE_URL}/api/v1/queries`,
  GET_ACTIVE_BANNERS: `${BASE_URL}/api/v1/banners/active`,
  SUBMIT_SUPPORT: `${BASE_URL}/api/v1/support/general`,
  SUBMIT_SUPPORT_ORDER: `${BASE_URL}/api/v1/support/order-query`,
};
