spring.application.name=backend
# H2 Database (TEMP - DEV ONLY)
spring.datasource.url=jdbc:mysql://localhost:3306/live?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# H2 console disabled when using MySQL
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly
jwt.expiration=86400000
server.port=8080

# AWS S3 Configuration
aws.s3.access-key-id=YOUR_ACCESS_KEY_ID
aws.s3.secret-access-key=YOUR_SECRET_ACCESS_KEY
aws.s3.region=ap-south-1
aws.s3.bucket-name=deliveryapp-product-images-2026

# AWS SNS Configuration (OTP SMS)
aws.sns.access-key-id=YOUR_ACCESS_KEY_ID
aws.sns.secret-access-key=YOUR_SECRET_ACCESS_KEY
aws.sns.region=ap-south-1


logging.level.web=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
